import { Language, QuestionConfig, HeatingType, ClimateZone, IncomeProfile } from './types';
import { Home, Building2, User, Thermometer, Sun, Warehouse, CheckCircle2, XCircle } from 'lucide-react';

export const SUPPORTED_LANGUAGES: Record<Language, { name: string, flag: string }> = {
  FR: { name: 'Français', flag: '🇫🇷' },
  EN: { name: 'English', flag: '🇬🇧' },
  DE: { name: 'Deutsch', flag: '🇩🇪' },
  NL: { name: 'Vlaams / Nederlands', flag: '🇧🇪' },
  NO: { name: 'Norsk', flag: '🇳🇴' },
  ES: { name: 'Español', flag: '🇪🇸' },
};

// =========================================
// OFFICIAL 2025 DATA (ANAH / MTE)
// =========================================

// Master Department Database based on your provided lists
export const DEPARTMENT_DB: Record<string, { name: string, zone: ClimateZone }> = {
    // H1
    '01': { name: 'Ain', zone: ClimateZone.H1 }, '02': { name: 'Aisne', zone: ClimateZone.H1 }, '03': { name: 'Allier', zone: ClimateZone.H1 }, '05': { name: 'Hautes Alpes', zone: ClimateZone.H1 },
    '08': { name: 'Ardennes', zone: ClimateZone.H1 }, '10': { name: 'Aube', zone: ClimateZone.H1 }, '14': { name: 'Calvados', zone: ClimateZone.H1 }, '15': { name: 'Cantal', zone: ClimateZone.H1 },
    '19': { name: 'Corrèze', zone: ClimateZone.H1 }, '21': { name: 'Côte d’Or', zone: ClimateZone.H1 }, '23': { name: 'Creuse', zone: ClimateZone.H1 }, '25': { name: 'Doubs', zone: ClimateZone.H1 },
    '27': { name: 'Eure', zone: ClimateZone.H1 }, '28': { name: 'Eure et Loir', zone: ClimateZone.H1 }, '38': { name: 'Isère', zone: ClimateZone.H1 }, '39': { name: 'Jura', zone: ClimateZone.H1 },
    '42': { name: 'Loire', zone: ClimateZone.H1 }, '43': { name: 'Haute Loire', zone: ClimateZone.H1 }, '45': { name: 'Loiret', zone: ClimateZone.H1 }, '51': { name: 'Marne', zone: ClimateZone.H1 },
    '52': { name: 'Haute Marne', zone: ClimateZone.H1 }, '54': { name: 'Meurthe et Moselle', zone: ClimateZone.H1 }, '55': { name: 'Meuse', zone: ClimateZone.H1 }, '57': { name: 'Moselle', zone: ClimateZone.H1 },
    '58': { name: 'Nièvre', zone: ClimateZone.H1 }, '59': { name: 'Nord', zone: ClimateZone.H1 }, '60': { name: 'Oise', zone: ClimateZone.H1 }, '61': { name: 'Orne', zone: ClimateZone.H1 },
    '62': { name: 'Pas de Calais', zone: ClimateZone.H1 }, '63': { name: 'Puy de Dôme', zone: ClimateZone.H1 }, '67': { name: 'Bas Rhin', zone: ClimateZone.H1 }, '68': { name: 'Haut Rhin', zone: ClimateZone.H1 },
    '69': { name: 'Rhône', zone: ClimateZone.H1 }, '70': { name: 'Haute Saône', zone: ClimateZone.H1 }, '71': { name: 'Saône et Loire', zone: ClimateZone.H1 }, '73': { name: 'Savoie', zone: ClimateZone.H1 },
    '74': { name: 'Haute Savoie', zone: ClimateZone.H1 }, '75': { name: 'Paris', zone: ClimateZone.H1 }, '76': { name: 'Seine Maritime', zone: ClimateZone.H1 }, '77': { name: 'Seine et Marne', zone: ClimateZone.H1 },
    '78': { name: 'Yvelines', zone: ClimateZone.H1 }, '80': { name: 'Somme', zone: ClimateZone.H1 }, '87': { name: 'Haute Vienne', zone: ClimateZone.H1 }, '88': { name: 'Vosges', zone: ClimateZone.H1 },
    '89': { name: 'Yonne', zone: ClimateZone.H1 }, '90': { name: 'Territoire de Belfort', zone: ClimateZone.H1 }, '91': { name: 'Essonne', zone: ClimateZone.H1 }, '92': { name: 'Hauts de Seine', zone: ClimateZone.H1 },
    '93': { name: 'Seine Saint Denis', zone: ClimateZone.H1 }, '94': { name: 'Val de Marne', zone: ClimateZone.H1 }, '95': { name: 'Val d’Oise', zone: ClimateZone.H1 },
    // H2
    '04': { name: 'Alpes de Haute Provence', zone: ClimateZone.H2 }, '07': { name: 'Ardèche', zone: ClimateZone.H2 }, '09': { name: 'Ariège', zone: ClimateZone.H2 }, '12': { name: 'Aveyron', zone: ClimateZone.H2 },
    '16': { name: 'Charente', zone: ClimateZone.H2 }, '17': { name: 'Charente Maritime', zone: ClimateZone.H2 }, '18': { name: 'Cher', zone: ClimateZone.H2 }, '22': { name: 'Côtes d’Armor', zone: ClimateZone.H2 },
    '24': { name: 'Dordogne', zone: ClimateZone.H2 }, '26': { name: 'Drôme', zone: ClimateZone.H2 }, '29': { name: 'Finistère', zone: ClimateZone.H2 }, '31': { name: 'Haute Garonne', zone: ClimateZone.H2 },
    '32': { name: 'Gers', zone: ClimateZone.H2 }, '33': { name: 'Gironde', zone: ClimateZone.H2 }, '35': { name: 'Ille et Vilaine', zone: ClimateZone.H2 }, '36': { name: 'Indre', zone: ClimateZone.H2 },
    '37': { name: 'Indre et Loire', zone: ClimateZone.H2 }, '40': { name: 'Landes', zone: ClimateZone.H2 }, '41': { name: 'Loir et Cher', zone: ClimateZone.H2 }, '44': { name: 'Loire Atlantique', zone: ClimateZone.H2 },
    '46': { name: 'Lot', zone: ClimateZone.H2 }, '47': { name: 'Lot et Garonne', zone: ClimateZone.H2 }, '48': { name: 'Lozère', zone: ClimateZone.H2 }, '49': { name: 'Maine et Loire', zone: ClimateZone.H2 },
    '50': { name: 'Manche', zone: ClimateZone.H2 }, '53': { name: 'Mayenne', zone: ClimateZone.H2 }, '56': { name: 'Morbihan', zone: ClimateZone.H2 }, '64': { name: 'Pyrénées Atlantiques', zone: ClimateZone.H2 },
    '65': { name: 'Hautes Pyrénées', zone: ClimateZone.H2 }, '72': { name: 'Sarthe', zone: ClimateZone.H2 }, '79': { name: 'Deux Sèvres', zone: ClimateZone.H2 }, '81': { name: 'Tarn', zone: ClimateZone.H2 },
    '82': { name: 'Tarn et Garonne', zone: ClimateZone.H2 }, '84': { name: 'Vaucluse', zone: ClimateZone.H2 }, '85': { name: 'Vendée', zone: ClimateZone.H2 }, '86': { name: 'Vienne', zone: ClimateZone.H2 },
    // H3
    '06': { name: 'Alpes Maritimes', zone: ClimateZone.H3 }, '11': { name: 'Aude', zone: ClimateZone.H3 }, '13': { name: 'Bouches Du Rhône', zone: ClimateZone.H3 }, '20': { name: 'Corse', zone: ClimateZone.H3 },
    '2A': { name: 'Corse-du-Sud', zone: ClimateZone.H3 }, '2B': { name: 'Haute-Corse', zone: ClimateZone.H3 }, '30': { name: 'Gard', zone: ClimateZone.H3 }, '34': { name: 'Hérault', zone: ClimateZone.H3 },
    '66': { name: 'Pyrénées Orientales', zone: ClimateZone.H3 }, '83': { name: 'Var', zone: ClimateZone.H3 },
};

export const ZONE_H1_DEPTS = Object.entries(DEPARTMENT_DB).filter(([_, data]) => data.zone === ClimateZone.H1).map(([code]) => code);
export const ZONE_H2_DEPTS = Object.entries(DEPARTMENT_DB).filter(([_, data]) => data.zone === ClimateZone.H2).map(([code]) => code);
export const ZONE_H3_DEPTS = Object.entries(DEPARTMENT_DB).filter(([_, data]) => data.zone === ClimateZone.H3).map(([code]) => code);

export const INCOME_CEILINGS_2025 = {
  IDF: {
    [IncomeProfile.BLUE]:   [23768, 34884, 41893, 48914, 55961], // +7038/pers
    [IncomeProfile.YELLOW]: [28933, 42463, 51000, 59549, 68123], // +8568/pers
    [IncomeProfile.VIOLET]: [40404, 59394, 71060, 83637, 95758], // +12122/pers
  },
  OTHER: {
    [IncomeProfile.BLUE]:   [17173, 25115, 30206, 35285, 40388], // +5094/pers
    [IncomeProfile.YELLOW]: [22015, 32197, 38719, 45234, 51775], // +6525/pers
    [IncomeProfile.VIOLET]: [30844, 45340, 54592, 63844, 73098], // +9254/pers
  }
};
export const INCOME_INCREMENTS = {
    IDF: { [IncomeProfile.BLUE]: 7038, [IncomeProfile.YELLOW]: 8568, [IncomeProfile.VIOLET]: 12122 },
    OTHER: { [IncomeProfile.BLUE]: 5094, [IncomeProfile.YELLOW]: 6525, [IncomeProfile.VIOLET]: 9254 }
};

// =========================================
// QUESTIONNAIRE SCRIPT
// =========================================

export const QUESTIONS: QuestionConfig[] = [
  {
    id: 'ownerStatus',
    type: 'radio',
    questionKey: 'q.status',
    options: [
      { value: 'owner', labelKey: 'opt.owner', icon: Home },
      { value: 'tenant_private', labelKey: 'opt.tenant_priv', icon: User },
      { value: 'tenant_social', labelKey: 'opt.tenant_soc', icon: Building2 },
    ]
  },
  {
    id: 'houseType',
    type: 'radio',
    questionKey: 'q.house_type',
    options: [
      { value: 'house', labelKey: 'opt.house', icon: Home },
      { value: 'apartment', labelKey: 'opt.apt', icon: Building2 },
    ]
  },
  {
      id: 'residenceType',
      type: 'radio',
      questionKey: 'q.residence_type',
      options: [
          { value: 'primary', labelKey: 'opt.primary', icon: Home },
          { value: 'secondary', labelKey: 'opt.secondary', icon: Warehouse },
      ]
  },
  {
    id: 'propertyAge',
    type: 'radio',
    questionKey: 'q.age',
    options: [
      { value: 'more_2y', labelKey: 'opt.more_2y' },
      { value: 'less_2y', labelKey: 'opt.less_2y' },
    ]
  },
  // Deprecated in wizard, now in sidebar, but kept if needed for old flows.
  // We will likely skip asking this in the wizard if it's already in the sidebar.
  // { id: 'department', type: 'department', questionKey: 'q.dept', placeholderKey: 'ph.dept' },
  {
    id: 'heatingType',
    type: 'select',
    questionKey: 'q.heating',
    options: [
      { value: HeatingType.ELECTRICITY, labelKey: 'opt.heat.elec', icon: Thermometer },
      { value: HeatingType.GAS, labelKey: 'opt.heat.gas', icon: Thermometer },
      { value: HeatingType.FUEL, labelKey: 'opt.heat.fuel', icon: Thermometer },
      { value: HeatingType.WOOD, labelKey: 'opt.heat.wood', icon: Thermometer },
      { value: HeatingType.HEAT_PUMP, labelKey: 'opt.heat.pac', icon: Thermometer },
      { value: HeatingType.OTHER, labelKey: 'opt.heat.other', icon: Thermometer },
    ]
  },
  {
      id: 'livingArea',
      type: 'number',
      questionKey: 'q.area',
      min: 10,
      suffixKey: 'm²'
  },
  // --- Technical Branch for ISO ---
  {
      id: 'atticArea',
      type: 'number',
      questionKey: 'q.attic_area',
      condition: (a) => a.houseType === 'house',
      min: 0,
      suffixKey: 'm²'
  },
   {
      id: 'atticAccess',
      type: 'radio',
      questionKey: 'q.attic_access',
      condition: (a) => a.houseType === 'house' && (a.atticArea || 0) >= 80,
      options: [
          { value: 'trapdoor', labelKey: 'opt.access.trap' },
          { value: 'plain_foot', labelKey: 'opt.access.plain' },
          { value: 'none', labelKey: 'opt.access.none' },
      ]
  },
  // --- Technical Branch for SSC (if has PAC) ---
  {
      id: 'roofSpaceAvailable',
      type: 'radio',
      questionKey: 'q.roof_space',
      condition: (a) => a.heatingType === HeatingType.HEAT_PUMP && a.houseType === 'house',
      options: [
          { value: true, labelKey: 'yes', icon: CheckCircle2 },
          { value: false, labelKey: 'no', icon: XCircle },
      ]
  },
  {
      id: 'roofOrientation',
      type: 'select',
      questionKey: 'q.orientation',
      condition: (a) => a.heatingType === HeatingType.HEAT_PUMP && a.houseType === 'house' && a.roofSpaceAvailable === true,
      options: [
          { value: 'SOUTH', labelKey: 'opt.orient.south', icon: Sun },
          { value: 'WEST', labelKey: 'opt.orient.west', icon: Sun },
          { value: 'EAST', labelKey: 'opt.orient.east', icon: Sun },
          { value: 'NORTH', labelKey: 'opt.orient.north', icon: Sun },
      ]
  },
  // --- Financials ---
  {
    id: 'householdSize',
    type: 'number',
    questionKey: 'q.people',
    min: 1,
    max: 15
  },
  {
    id: 'income',
    type: 'number',
    questionKey: 'q.income',
    min: 0,
    suffixKey: '€/an',
    infoKey: 'info.rfr'
  }
];

// =========================================
// TRANSLATIONS (GOVERNMENT STANDARD)
// =========================================

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  FR: {
    'app.title': 'France Rénov\' - Portail d\'Éligibilité Officiel',
    'header.subtitle': 'Vérification conforme aux barèmes de l\'État 2025',
    'sidebar.title': 'DOSSIER CANDIDAT',
    'sidebar.fname': 'Prénom',
    'sidebar.lname': 'Nom',
    'sidebar.phone': 'Téléphone',
    'sidebar.email': 'Email',
    'sidebar.address': 'Adresse Postale',
    'sidebar.cp': 'Code Postal',
    'sidebar.city': 'Ville / Commune',
    'sidebar.zone': 'Zone Détectée',
    'btn.start': 'Démarrer l\'évaluation',
    'btn.next': 'Question suivante',
    'btn.prev': 'Retour',
    'btn.calculate': 'Voir mon rapport officiel',
    'btn.restart': 'Nouvelle évaluation',
    'btn.download_txt': 'Télécharger le Rapport (.txt)',
    'btn.view_income': 'Voir les Plafonds 2025',
    'btn.view_zones': 'Voir les Zones H1/H2/H3',
    'modal.income.title': 'Barèmes Officiels ANAH 2025',
    'modal.zones.title': 'Zones Climatiques Officielles',
    'yes': 'Oui',
    'no': 'Non',

    // Questions
    'q.status': 'Quel est votre statut d\'occupation ?',
    'q.house_type': 'Type de logement concerné :',
    'q.residence_type': 'Est-ce votre résidence principale ?',
    'q.age': 'Ancienneté du logement :',
    'q.dept': 'Département du logement (ex: 75) :',
    'q.heating': 'Énergie de chauffage PRINCIPALE actuelle :',
    'q.area': 'Surface habitable totale chauffée :',
    'q.attic_area': 'Surface de vos combles PERDUS :',
    'q.attic_access': 'Accès aux combles :',
    'q.roof_space': 'Disposez-vous de 8m² de toiture libre ?',
    'q.orientation': 'Orientation principale de ce pan de toiture :',
    'q.people': 'Nombre de personnes sur votre avis d\'imposition :',
    'q.income': 'Revenu Fiscal de Référence (RFR) du foyer :',

    // Options
    'opt.owner': 'Propriétaire occupant / bailleur',
    'opt.tenant_priv': 'Locataire (parc privé)',
    'opt.tenant_soc': 'Locataire (HLM / social)',
    'opt.house': 'Maison individuelle',
    'opt.apt': 'Appartement / Copropriété',
    'opt.primary': 'Résidence Principale',
    'opt.secondary': 'Résidence Secondaire',
    'opt.more_2y': 'Plus de 2 ans',
    'opt.less_2y': 'Moins de 2 ans',
    'opt.heat.elec': 'Électricité (radiateurs, base)',
    'opt.heat.gas': 'Gaz (ville ou citerne)',
    'opt.heat.fuel': 'Fioul',
    'opt.heat.wood': 'Bois / Biomasse',
    'opt.heat.pac': 'Pompe à Chaleur (déjà installée)',
    'opt.heat.other': 'Autre',
    'opt.access.trap': 'Trappe de visite (≥ 50x50cm)',
    'opt.access.plain': 'Aucun (plain-pied, accès par toiture possible)',
    'opt.access.none': 'Inaccessible',
    'opt.orient.south': 'Sud',
    'opt.orient.west': 'Ouest',
    'opt.orient.east': 'Est',
    'opt.orient.north': 'Nord',

    // Info & Placeholders
    'ph.dept': 'Numéro (ex: 06, 75...)',
    'info.rfr': 'Indiqué sur votre dernier avis d\'impôt (ligne 25).',

    // Report & Justifications
    'report.title': 'RAPPORT D\'ÉLIGIBILITÉ OFFICIEL',
    'report.id': 'Dossier N°',
    'report.personal': 'DÉTAILS PERSONNELS DU CANDIDAT',
    'report.profile': 'PROFIL ADMINISTRATIF',
    'report.zone': 'Zone Climatique :',
    'report.income_cat': 'Catégorie Ménage :',
    'report.eligible_global': 'AVIS FAVORABLE',
    'report.ineligible_global': 'AVIS DÉFAVORABLE',
    'report.summary_eligible': 'Votre situation vous permet de bénéficier des dispositifs d\'État ci-dessous.',
    'report.summary_ineligible': 'Votre situation ne répond pas aux critères actuels des principaux dispositifs.',

    'scheme.pac101': 'Offre "Coup de Pouce" PAC',
    'scheme.iso101': 'Isolation des Combles à 1€',
    'scheme.ssc': 'Système Solaire Combiné (SSC)',
    'scheme.mpr': 'MaPrimeRénov\' (Parcours classique)',
    'scheme.cee': 'Certificats Économies d\'Énergie (CEE)',

    'reason.ok_zone_h1': '✅ Zone H1 prioritaire pour ce dispositif.',
    'reason.ok_zone_eligible': '✅ Zone climatique éligible (H1 ou H2).',
    'reason.ok_income_blue': '✅ Revenus "Très Modestes" (Bleu) éligibles au taux maximal.',
    'reason.ok_owner': '✅ Statut de propriétaire validé.',
    'reason.ok_house_age': '✅ Logement de plus de 2 ans.',
    'reason.ok_surface': '✅ Surface suffisante pour ce dispositif.',
    'reason.ok_heating_replace': '✅ Remplacement d\'un chauffage polluant encouragé.',
    'reason.ok_tech_iso': '✅ Critères techniques combles validés (>80m², accès OK).',
    'reason.ok_tech_ssc': '✅ Toiture compatible solaire validée.',

    'reason.fail_zone': '❌ Zone climatique non prioritaire pour cette offre spécifique.',
    'reason.fail_income_too_high': '❌ Revenus supérieurs au plafond réglementaire pour cette aide.',
    'reason.fail_tenant_social': '❌ Dispositif non applicable aux logements sociaux (bailleurs HLM uniquement).',
    'reason.fail_apartment': '❌ Offre réservée aux maisons individuelles.',
    'reason.fail_new_build': '❌ Logement trop récent (< 2 ans).',
    'reason.fail_elec_heating': '❌ Le remplacement de chauffage électrique n\'est pas subventionné par ce dispositif.',
    'reason.fail_surface_low': '❌ Surface insuffisante pour viabilité économique du dispositif.',
    'reason.fail_already_pac': '❌ Vous disposez déjà d\'une Pompe à Chaleur.',
    'reason.fail_tech_iso': '❌ Contraintes techniques combles (surface <80m² ou accès impossible).',
    'reason.fail_tech_ssc': '❌ Incompatible (Orientation Nord ou surface insuffisante).',
  },
  EN: {
    'app.title': 'France Rénov\' - Official Eligibility Portal',
    'header.subtitle': 'Verification compliant with 2025 State standards',
    'sidebar.title': 'CANDIDATE FILE',
    'sidebar.fname': 'First Name',
    'sidebar.lname': 'Last Name',
    'sidebar.phone': 'Phone',
    'sidebar.email': 'Email',
    'sidebar.address': 'Street Address',
    'sidebar.cp': 'Postal Code',
    'sidebar.city': 'City / Town',
    'sidebar.zone': 'Detected Zone',
    'btn.start': 'Start Assessment',
    'btn.next': 'Next Question',
    'btn.prev': 'Back',
    'btn.calculate': 'View Official Report',
    'btn.restart': 'New Assessment',
    'btn.download_txt': 'Download Report (.txt)',
    'btn.view_income': 'View 2025 Income Tables',
    'btn.view_zones': 'View Zone Tables (H1/H2/H3)',
    'modal.income.title': 'Official ANAH 2025 Thresholds',
    'modal.zones.title': 'Official Climate Zones',
    'yes': 'Yes',
    'no': 'No',
    'q.status': 'What is your occupancy status?',
    'q.house_type': 'Type of housing concerned:',
    'q.residence_type': 'Is this your primary residence?',
    'q.age': 'Property age:',
    'q.dept': 'Department number (e.g., 75):',
    'q.heating': 'Current MAIN heating energy:',
    'q.area': 'Total heated living area:',
    'q.attic_area': 'Surface of LOST attics:',
    'q.attic_access': 'Attic access:',
    'q.roof_space': 'Do you have 8m² of free roof space?',
    'q.orientation': 'Main orientation of this roof section:',
    'q.people': 'Number of people in household:',
    'q.income': 'Reference Tax Income (RFR):',
    'opt.owner': 'Owner-occupier / Landlord',
    'opt.tenant_priv': 'Tenant (private sector)',
    'opt.tenant_soc': 'Tenant (social housing)',
    'opt.house': 'Detached house',
    'opt.apt': 'Apartment / Condo',
    'opt.primary': 'Primary Residence',
    'opt.secondary': 'Secondary Residence',
    'opt.more_2y': 'More than 2 years',
    'opt.less_2y': 'Less than 2 years',
    'opt.heat.elec': 'Electricity (base radiators)',
    'opt.heat.gas': 'Gas (mains or tank)',
    'opt.heat.fuel': 'Oil / Fuel',
    'opt.heat.wood': 'Wood / Biomass',
    'opt.heat.pac': 'Heat Pump (already installed)',
    'opt.heat.other': 'Other',
    'opt.access.trap': 'Inspection hatch (≥ 50x50cm)',
    'opt.access.plain': 'None (single-storey, roof access ok)',
    'opt.access.none': 'Inaccessible',
    'opt.orient.south': 'South',
    'opt.orient.west': 'West',
    'opt.orient.east': 'East',
    'opt.orient.north': 'North',
    'ph.dept': 'Number (e.g. 06, 75...)',
    'info.rfr': 'Indicated on your last tax notice (line 25).',
    'report.title': 'OFFICIAL ELIGIBILITY REPORT',
    'report.id': 'File N°',
    'report.personal': 'CANDIDATE PERSONAL DETAILS',
    'report.profile': 'ADMINISTRATIVE PROFILE',
    'report.zone': 'Climate Zone:',
    'report.income_cat': 'Household Category:',
    'report.eligible_global': 'FAVORABLE OPINION',
    'report.ineligible_global': 'UNFAVORABLE OPINION',
    'report.summary_eligible': 'Your situation allows you to benefit from the State schemes below.',
    'report.summary_ineligible': 'Your situation does not meet current criteria for main schemes.',
    'scheme.pac101': '"Heat Pump Boost" Offer',
    'scheme.iso101': '€1 Attic Insulation',
    'scheme.ssc': 'Combined Solar System (SSC)',
    'scheme.mpr': 'MaPrimeRénov\' (Standard)',
    'scheme.cee': 'Energy Savings Certificates (CEE)',
    'reason.ok_zone_h1': '✅ H1 Zone priority for this scheme.',
    'reason.ok_zone_eligible': '✅ Eligible climate zone (H1 or H2).',
    'reason.ok_income_blue': '✅ "Very Modest" (Blue) income eligible for max rate.',
    'reason.ok_owner': '✅ Owner status validated.',
    'reason.ok_house_age': '✅ Property older than 2 years.',
    'reason.ok_surface': '✅ Sufficient surface area for this scheme.',
    'reason.ok_heating_replace': '✅ Replacement of polluting heating encouraged.',
    'reason.ok_tech_iso': '✅ Attic technical criteria validated (>80m², access OK).',
    'reason.ok_tech_ssc': '✅ Solar compatible roof validated.',
    'reason.fail_zone': '❌ Climate zone not priority for this specific offer.',
    'reason.fail_income_too_high': '❌ Income exceeds regulatory ceiling for this aid.',
    'reason.fail_tenant_social': '❌ Scheme not applicable to social housing (HLM landlords only).',
    'reason.fail_apartment': '❌ Offer reserved for detached houses.',
    'reason.fail_new_build': '❌ Property too new (< 2 years).',
    'reason.fail_elec_heating': '❌ Electric heating replacement not subsidized by this scheme.',
    'reason.fail_surface_low': '❌ Insufficient surface area for economic viability.',
    'reason.fail_already_pac': '❌ You already have a Heat Pump.',
    'reason.fail_tech_iso': '❌ Attic technical constraints (area <80m² or no access).',
    'reason.fail_tech_ssc': '❌ Incompatible roof (North orientation or insufficient area).',
  },
  DE: {
      'app.title': 'France Rénov\' - Offizielles Berechtigungsportal',
      'header.subtitle': 'Prüfung gemäß staatlichen Standards 2025',
      'sidebar.title': 'KANDIDATENAKTE',
      'sidebar.fname': 'Vorname',
      'sidebar.lname': 'Nachname',
      'sidebar.phone': 'Telefon',
      'sidebar.email': 'E-Mail',
      'sidebar.address': 'Anschrift',
      'sidebar.cp': 'Postleitzahl',
      'sidebar.city': 'Stadt / Gemeinde',
      'sidebar.zone': 'Erkannte Zone',
      'btn.start': 'Bewertung starten',
      'btn.next': 'Nächste Frage',
      'btn.prev': 'Zurück',
      'btn.calculate': 'Offiziellen Bericht ansehen',
      'btn.restart': 'Neue Bewertung',
      'btn.download_txt': 'Bericht herunterladen (.txt)',
      'btn.view_income': 'Einkommenstabellen 2025 ansehen',
      'btn.view_zones': 'Zonentabellen ansehen (H1/H2/H3)',
      'modal.income.title': 'Offizielle ANAH-Grenzwerte 2025',
      'modal.zones.title': 'Offizielle Klimazonen',
      'yes': 'Ja',
      'no': 'Nein',
      'q.status': 'Was ist Ihr Belegungsstatus?',
      'q.house_type': 'Art der betroffenen Unterkunft:',
      'q.residence_type': 'Ist dies Ihr Hauptwohnsitz?',
      'q.age': 'Alter der Immobilie:',
      'q.dept': 'Département-Nummer (z.B. 75):',
      'q.heating': 'Aktuelle HAUPTHEIZENERGIE:',
      'q.area': 'Beheizte Wohnfläche gesamt:',
      'q.attic_area': 'Fläche des VERLORENEN Dachbodens:',
      'q.attic_access': 'Zugang zum Dachboden:',
      'q.roof_space': 'Haben Sie 8m² freie Dachfläche?',
      'q.orientation': 'Hauptausrichtung dieses Dachteils:',
      'q.people': 'Anzahl der Personen im Haushalt:',
      'q.income': 'Steuerliches Referenzeinkommen (RFR):',
      'opt.owner': 'Eigentümer / Vermieter',
      'opt.tenant_priv': 'Mieter (Privatsektor)',
      'opt.tenant_soc': 'Mieter (Sozialwohnungen)',
      'opt.house': 'Einfamilienhaus',
      'opt.apt': 'Wohnung / Eigentumswohnung',
      'opt.primary': 'Hauptwohnsitz',
      'opt.secondary': 'Zweitwohnsitz',
      'opt.more_2y': 'Mehr als 2 Jahre',
      'opt.less_2y': 'Weniger als 2 Jahre',
      'opt.heat.elec': 'Elektrizität (Basisheizkörper)',
      'opt.heat.gas': 'Gas (Stadt oder Tank)',
      'opt.heat.fuel': 'Öl / Brennstoff',
      'opt.heat.wood': 'Holz / Biomasse',
      'opt.heat.pac': 'Wärmepumpe (bereits installiert)',
      'opt.heat.other': 'Andere',
      'opt.access.trap': 'Inspektionsluke (≥ 50x50cm)',
      'opt.access.plain': 'Keiner (ebenerdig, Dachzugang ok)',
      'opt.access.none': 'Unzugänglich',
      'opt.orient.south': 'Süd',
      'opt.orient.west': 'West',
      'opt.orient.east': 'Ost',
      'opt.orient.north': 'Nord',
      'ph.dept': 'Nummer (z.B. 06, 75...)',
      'info.rfr': 'Angegeben auf Ihrem letzten Steuerbescheid (Zeile 25).',
      'report.title': 'OFFIZIELLER BERECHTIGUNGSBERICHT',
      'report.id': 'Aktenzeichen',
      'report.personal': 'PERSÖNLICHE ANGABEN DES KANDIDATEN',
      'report.profile': 'VERWALTUNGSPROFIL',
      'report.zone': 'Klimazone:',
      'report.income_cat': 'Haushaltskategorie:',
      'report.eligible_global': 'POSITIVE STELLUNGNAHME',
      'report.ineligible_global': 'NEGATIVE STELLUNGNAHME',
      'report.summary_eligible': 'Ihre Situation ermöglicht es Ihnen, von den folgenden staatlichen Programmen zu profitieren.',
      'report.summary_ineligible': 'Ihre Situation entspricht nicht den aktuellen Kriterien für Hauptprogramme.',
      'scheme.pac101': 'Angebot "Wärmepumpen-Bonus"',
      'scheme.iso101': '1€ Dachbodendämmung',
      'scheme.ssc': 'Kombiniertes Solarsystem (SSC)',
      'scheme.mpr': 'MaPrimeRénov\' (Standard)',
      'scheme.cee': 'Energiesparzertifikate (CEE)',
      'reason.ok_zone_h1': '✅ Zone H1 Priorität für dieses Programm.',
      'reason.ok_zone_eligible': '✅ Berechtigte Klimazone (H1 oder H2).',
      'reason.ok_income_blue': '✅ Einkommen "Sehr bescheiden" (Blau) für Höchstsatz berechtigt.',
      'reason.ok_owner': '✅ Eigentümerstatus validiert.',
      'reason.ok_house_age': '✅ Immobilie älter als 2 Jahre.',
      'reason.ok_surface': '✅ Ausreichende Fläche für dieses Programm.',
      'reason.ok_heating_replace': '✅ Austausch von umweltschädlicher Heizung gefördert.',
      'reason.ok_tech_iso': '✅ Technische Kriterien Dachboden validiert (>80m², Zugang OK).',
      'reason.ok_tech_ssc': '✅ Solarkompatibles Dach validiert.',
      'reason.fail_zone': '❌ Klimazone keine Priorität für dieses spezielle Angebot.',
      'reason.fail_income_too_high': '❌ Einkommen übersteigt die gesetzliche Obergrenze für diese Hilfe.',
      'reason.fail_tenant_social': '❌ Programm nicht anwendbar auf Sozialwohnungen.',
      'reason.fail_apartment': '❌ Angebot nur für Einfamilienhäuser.',
      'reason.fail_new_build': '❌ Immobilie zu neu (< 2 Jahre).',
      'reason.fail_elec_heating': '❌ Austausch von Elektroheizungen wird durch dieses Programm nicht subventioniert.',
      'reason.fail_surface_low': '❌ Unzureichende Fläche für wirtschaftliche Tragfähigkeit.',
      'reason.fail_already_pac': '❌ Sie haben bereits eine Wärmepumpe.',
      'reason.fail_tech_iso': '❌ Technische Einschränkungen Dachboden (Fläche <80m² oder kein Zugang).',
      'reason.fail_tech_ssc': '❌ Inkompatibles Dach (Nordausrichtung oder unzureichende Fläche).',
  },
  NL: {
      'app.title': 'France Rénov\' - Officieel Geschiktheidsportaal',
      'header.subtitle': 'Verificatie conform staatsnormen 2025',
      'sidebar.title': 'KANDIDAAT DOSSIER',
      'sidebar.fname': 'Voornaam',
      'sidebar.lname': 'Achternaam',
      'sidebar.phone': 'Telefoon',
      'sidebar.email': 'E-mail',
      'sidebar.address': 'Adres',
      'sidebar.cp': 'Postcode',
      'sidebar.city': 'Stad / Gemeente',
      'sidebar.zone': 'Gedetecteerde Zone',
      'btn.start': 'Start Beoordeling',
      'btn.next': 'Volgende Vraag',
      'btn.prev': 'Terug',
      'btn.calculate': 'Bekijk Officieel Rapport',
      'btn.restart': 'Nieuwe Beoordeling',
      'btn.download_txt': 'Rapport Downloaden (.txt)',
      'btn.view_income': 'Bekijk Inkomenstabellen 2025',
      'btn.view_zones': 'Bekijk Zonetabellen (H1/H2/H3)',
      'modal.income.title': 'Officiële ANAH Drempels 2025',
      'modal.zones.title': 'Officiële Klimaatzones',
      'yes': 'Ja',
      'no': 'Nee',
      'q.status': 'Wat is uw bewoningsstatus?',
      'q.house_type': 'Type betreffende woning:',
      'q.residence_type': 'Is dit uw hoofdverblijf?',
      'q.age': 'Leeftijd van de woning:',
      'q.dept': 'Departement nummer (bijv. 75):',
      'q.heating': 'Huidige HOOFD verwarmingsenergie:',
      'q.area': 'Totale verwarmde woonoppervlakte:',
      'q.attic_area': 'Oppervlakte van VERLOREN zolders:',
      'q.attic_access': 'Toegang tot zolder:',
      'q.roof_space': 'Heeft u 8m² vrije dakoppervlakte?',
      'q.orientation': 'Hoofdoriëntatie van dit dakdeel:',
      'q.people': 'Aantal personen in huishouden:',
      'q.income': 'Fiscaal Referentie Inkomen (RFR):',
      'opt.owner': 'Eigenaar-bewoner / Verhuurder',
      'opt.tenant_priv': 'Huurder (private sector)',
      'opt.tenant_soc': 'Huurder (sociale huur)',
      'opt.house': 'Vrijstaand huis',
      'opt.apt': 'Appartement',
      'opt.primary': 'Hoofdverblijf',
      'opt.secondary': 'Tweede Woning',
      'opt.more_2y': 'Meer dan 2 jaar',
      'opt.less_2y': 'Minder dan 2 jaar',
      'opt.heat.elec': 'Elektriciteit (basisradiatoren)',
      'opt.heat.gas': 'Gas (stad of tank)',
      'opt.heat.fuel': 'Stookolie',
      'opt.heat.wood': 'Hout / Biomassa',
      'opt.heat.pac': 'Warmtepomp (al geïnstalleerd)',
      'opt.heat.other': 'Anders',
      'opt.access.trap': 'Inspectieluik (≥ 50x50cm)',
      'opt.access.plain': 'Geen (gelijkvloers, daktoegang ok)',
      'opt.access.none': 'Ontoegankelijk',
      'opt.orient.south': 'Zuid',
      'opt.orient.west': 'West',
      'opt.orient.east': 'Oost',
      'opt.orient.north': 'Noord',
      'ph.dept': 'Nummer (bijv. 06, 75...)',
      'info.rfr': 'Aangegeven op uw laatste belastingaanslag (regel 25).',
      'report.title': 'OFFICIEEL GESCHIKTHEIDSRAPPORT',
      'report.id': 'Dossier Nr.',
      'report.personal': 'PERSOONLIJKE GEGEVENS KANDIDAAT',
      'report.profile': 'ADMINISTRATIEF PROFIEL',
      'report.zone': 'Klimaatzone:',
      'report.income_cat': 'Huishoudcategorie:',
      'report.eligible_global': 'GUNSTIG ADVIES',
      'report.ineligible_global': 'ONGUNSTIG ADVIES',
      'report.summary_eligible': 'Uw situatie stelt u in staat te profiteren van de onderstaande staatsregelingen.',
      'report.summary_ineligible': 'Uw situatie voldoet niet aan de huidige criteria voor hoofdregelingen.',
      'scheme.pac101': 'Aanbieding "Warmtepomp Boost"',
      'scheme.iso101': '1€ Zolderisolatie',
      'scheme.ssc': 'Gecombineerd Zonne-systeem (SSC)',
      'scheme.mpr': 'MaPrimeRénov\' (Standaard)',
      'scheme.cee': 'Energiebesparingscertificaten (CEE)',
      'reason.ok_zone_h1': '✅ Zone H1 prioriteit voor deze regeling.',
      'reason.ok_zone_eligible': '✅ Geschikte klimaatzone (H1 of H2).',
      'reason.ok_income_blue': '✅ Inkomen "Zeer Bescheiden" (Blauw) komt in aanmerking voor max tarief.',
      'reason.ok_owner': '✅ Eigenaarsstatus gevalideerd.',
      'reason.ok_house_age': '✅ Woning ouder dan 2 jaar.',
      'reason.ok_surface': '✅ Voldoende oppervlakte voor deze regeling.',
      'reason.ok_heating_replace': '✅ Vervanging van vervuilende verwarming aangemoedigd.',
      'reason.ok_tech_iso': '✅ Technische criteria zolder gevalideerd (>80m², toegang OK).',
      'reason.ok_tech_ssc': '✅ Zon-compatibel dak gevalideerd.',
      'reason.fail_zone': '❌ Klimaatzone geen prioriteit voor dit specifieke aanbod.',
      'reason.fail_income_too_high': '❌ Inkomen overschrijdt wettelijk plafond voor deze hulp.',
      'reason.fail_tenant_social': '❌ Regeling niet van toepassing op sociale huurwoningen.',
      'reason.fail_apartment': '❌ Aanbod gereserveerd voor vrijstaande huizen.',
      'reason.fail_new_build': '❌ Woning te nieuw (< 2 jaar).',
      'reason.fail_elec_heating': '❌ Vervanging van elektrische verwarming wordt niet gesubsidieerd.',
      'reason.fail_surface_low': '❌ Onvoldoende oppervlakte voor economische levensvatbaarheid.',
      'reason.fail_already_pac': '❌ U heeft al een warmtepomp.',
      'reason.fail_tech_iso': '❌ Technische beperkingen zolder (opp <80m² of geen toegang).',
      'reason.fail_tech_ssc': '❌ Incompatibel dak (Noordoriëntatie of onvoldoende oppervlakte).',
  },
  NO: {
      'app.title': 'France Rénov\' - Offisiell Kvalifiseringsportal',
      'header.subtitle': 'Verifisering i samsvar med statlige standarder for 2025',
      'sidebar.title': 'KANDIDATFIL',
      'sidebar.fname': 'Fornavn',
      'sidebar.lname': 'Etternavn',
      'sidebar.phone': 'Telefon',
      'sidebar.email': 'E-post',
      'sidebar.address': 'Adresse',
      'sidebar.cp': 'Postnummer',
      'sidebar.city': 'By / Tettsted',
      'sidebar.zone': 'Oppdaget Sone',
      'btn.start': 'Start Vurdering',
      'btn.next': 'Neste Spørsmål',
      'btn.prev': 'Tilbake',
      'btn.calculate': 'Se Offisiell Rapport',
      'btn.restart': 'Ny Vurdering',
      'btn.download_txt': 'Last ned Rapport (.txt)',
      'btn.view_income': 'Se Inntektstabeller 2025',
      'btn.view_zones': 'Se Sonetabeller (H1/H2/H3)',
      'modal.income.title': 'Offisielle ANAH-terskler 2025',
      'modal.zones.title': 'Offisielle Klimasoner',
      'yes': 'Ja',
      'no': 'Nei',
      'q.status': 'Hva er din boligstatus?',
      'q.house_type': 'Type bolig det gjelder:',
      'q.residence_type': 'Er dette din primærbolig?',
      'q.age': 'Boligens alder:',
      'q.dept': 'Departementsnummer (f.eks. 75):',
      'q.heating': 'Nåværende HOVEDoppvarmingsenergi:',
      'q.area': 'Totalt oppvarmet boareal:',
      'q.attic_area': 'Areal av TAPT loft:',
      'q.attic_access': 'Tilgang til loft:',
      'q.roof_space': 'Har du 8m² ledig takareal?',
      'q.orientation': 'Hovedorientering av denne takdelen:',
      'q.people': 'Antall personer i husstanden:',
      'q.income': 'Referanseskatteinntekt (RFR):',
      'opt.owner': 'Eier-beboer / Utleier',
      'opt.tenant_priv': 'Leietaker (privat sektor)',
      'opt.tenant_soc': 'Leietaker (sosialbolig)',
      'opt.house': 'Enebolig',
      'opt.apt': 'Leilighet / Sameie',
      'opt.primary': 'Primærbolig',
      'opt.secondary': 'Sekundærbolig',
      'opt.more_2y': 'Mer enn 2 år',
      'opt.less_2y': 'Mindre enn 2 år',
      'opt.heat.elec': 'Elektrisitet (basis radiatorer)',
      'opt.heat.gas': 'Gass (by eller tank)',
      'opt.heat.fuel': 'Olje / Drivstoff',
      'opt.heat.wood': 'Ved / Biomasse',
      'opt.heat.pac': 'Varmepumpe (allerede installert)',
      'opt.heat.other': 'Annet',
      'opt.access.trap': 'Inspeksjonsluke (≥ 50x50cm)',
      'opt.access.plain': 'Ingen (ettplan, taktilgang ok)',
      'opt.access.none': 'Utilgjengelig',
      'opt.orient.south': 'Sør',
      'opt.orient.west': 'Vest',
      'opt.orient.east': 'Øst',
      'opt.orient.north': 'Nord',
      'ph.dept': 'Nummer (f.eks. 06, 75...)',
      'info.rfr': 'Angitt på din siste skattemelding (linje 25).',
      'report.title': 'OFFISIELL KVALIFISERINGSRAPPORT',
      'report.id': 'Saksnr.',
      'report.personal': 'KANDIDATENS PERSONLIGE DETALJER',
      'report.profile': 'ADMINISTRATIV PROFIL',
      'report.zone': 'Klimasone:',
      'report.income_cat': 'Husholdningskategori:',
      'report.eligible_global': 'GUNSTIG UTTALELSE',
      'report.ineligible_global': 'UGUNSTIG UTTALELSE',
      'report.summary_eligible': 'Din situasjon lar deg dra nytte av de statlige ordningene nedenfor.',
      'report.summary_ineligible': 'Din situasjon oppfyller ikke gjeldende kriterier for hovedordninger.',
      'scheme.pac101': 'Tilbud "Varmepumpe Boost"',
      'scheme.iso101': '1€ Loftisolering',
      'scheme.ssc': 'Kombinert Solcellesystem (SSC)',
      'scheme.mpr': 'MaPrimeRénov\' (Standard)',
      'scheme.cee': 'Energisparebevis (CEE)',
      'reason.ok_zone_h1': '✅ Sone H1 prioritet for denne ordningen.',
      'reason.ok_zone_eligible': '✅ Kvalifisert klimasone (H1 eller H2).',
      'reason.ok_income_blue': '✅ Inntekt "Veldig Beskjeden" (Blå) kvalifisert for maks sats.',
      'reason.ok_owner': '✅ Eierstatus validert.',
      'reason.ok_house_age': '✅ Bolig eldre enn 2 år.',
      'reason.ok_surface': '✅ Tilstrekkelig areal for denne ordningen.',
      'reason.ok_heating_replace': '✅ Utskifting av forurensende oppvarming oppmuntres.',
      'reason.ok_tech_iso': '✅ Tekniske kriterier loft validert (>80m², tilgang OK).',
      'reason.ok_tech_ssc': '✅ Solkompatibelt tak validert.',
      'reason.fail_zone': '❌ Klimasone ikke prioritert for dette spesifikke tilbudet.',
      'reason.fail_income_too_high': '❌ Inntekt overstiger forskriftsmessig tak for denne støtten.',
      'reason.fail_tenant_social': '❌ Ordning gjelder ikke for sosialboliger.',
      'reason.fail_apartment': '❌ Tilbud forbeholdt eneboliger.',
      'reason.fail_new_build': '❌ Bolig for ny (< 2 år).',
      'reason.fail_elec_heating': '❌ Utskifting av elektrisk oppvarming subsidieres ikke.',
      'reason.fail_surface_low': '❌ Utilstrekkelig areal for økonomisk levedyktighet.',
      'reason.fail_already_pac': '❌ Du har allerede en varmepumpe.',
      'reason.fail_tech_iso': '❌ Tekniske begrensninger loft (areal <80m² eller ingen tilgang).',
      'reason.fail_tech_ssc': '❌ Inkompatibelt tak (Nordorientering eller utilstrekkelig areal).',
  },
  ES: {
      'app.title': 'France Rénov\' - Portal Oficial de Elegibilidad',
      'header.subtitle': 'Verificación conforme a estándares estatales 2025',
      'sidebar.title': 'EXPEDIENTE CANDIDATO',
      'sidebar.fname': 'Nombre',
      'sidebar.lname': 'Apellido',
      'sidebar.phone': 'Teléfono',
      'sidebar.email': 'Email',
      'sidebar.address': 'Dirección',
      'sidebar.cp': 'Código Postal',
      'sidebar.city': 'Ciudad / Municipio',
      'sidebar.zone': 'Zona Detectada',
      'btn.start': 'Iniciar Evaluación',
      'btn.next': 'Siguiente Pregunta',
      'btn.prev': 'Atrás',
      'btn.calculate': 'Ver Informe Oficial',
      'btn.restart': 'Nueva Evaluación',
      'btn.download_txt': 'Descargar Informe (.txt)',
      'btn.view_income': 'Ver Tablas de Ingresos 2025',
      'btn.view_zones': 'Ver Tablas de Zonas (H1/H2/H3)',
      'modal.income.title': 'Umbrales Oficiales ANAH 2025',
      'modal.zones.title': 'Zonas Climáticas Oficiales',
      'yes': 'Sí',
      'no': 'No',
      'q.status': '¿Cuál es su estado de ocupación?',
      'q.house_type': 'Tipo de vivienda afectada:',
      'q.residence_type': '¿Es esta su residencia principal?',
      'q.age': 'Antigüedad de la propiedad:',
      'q.dept': 'Número de departamento (ej. 75):',
      'q.heating': 'Energía de calefacción PRINCIPAL actual:',
      'q.area': 'Superficie habitable total calentada:',
      'q.attic_area': 'Superficie de áticos PERDIDOS:',
      'q.attic_access': 'Acceso al ático:',
      'q.roof_space': '¿Dispone de 8m² de techo libre?',
      'q.orientation': 'Orientación principal de esta sección del techo:',
      'q.people': 'Número de personas en el hogar:',
      'q.income': 'Ingreso Fiscal de Referencia (RFR):',
      'opt.owner': 'Propietario ocupante / Arrendador',
      'opt.tenant_priv': 'Inquilino (sector privado)',
      'opt.tenant_soc': 'Inquilino (vivienda social)',
      'opt.house': 'Casa unifamiliar',
      'opt.apt': 'Apartamento / Condominio',
      'opt.primary': 'Residencia Principal',
      'opt.secondary': 'Residencia Secundaria',
      'opt.more_2y': 'Más de 2 años',
      'opt.less_2y': 'Menos de 2 años',
      'opt.heat.elec': 'Electricidad (radiadores base)',
      'opt.heat.gas': 'Gas (ciudad o tanque)',
      'opt.heat.fuel': 'Gasóleo / Combustible',
      'opt.heat.wood': 'Madera / Biomasse',
      'opt.heat.pac': 'Bomba de Calor (ya instalada)',
      'opt.heat.other': 'Otro',
      'opt.access.trap': 'Trampilla de inspección (≥ 50x50cm)',
      'opt.access.plain': 'Ninguno (planta baja, acceso techo ok)',
      'opt.access.none': 'Inaccesible',
      'opt.orient.south': 'Sur',
      'opt.orient.west': 'Oeste',
      'opt.orient.east': 'Este',
      'opt.orient.north': 'Norte',
      'ph.dept': 'Número (ej. 06, 75...)',
      'info.rfr': 'Indicado en su último aviso fiscal (línea 25).',
      'report.title': 'INFORME OFICIAL DE ELEGIBILIDAD',
      'report.id': 'Expediente N°',
      'report.personal': 'DETALLES PERSONALES DEL CANDIDATO',
      'report.profile': 'PERFIL ADMINISTRATIVO',
      'report.zone': 'Zona Climática:',
      'report.income_cat': 'Categoría del Hogar:',
      'report.eligible_global': 'OPINIÓN FAVORABLE',
      'report.ineligible_global': 'OPINIÓN DESFAVORABLE',
      'report.summary_eligible': 'Su situación le permite beneficiarse de los esquemas estatales a continuación.',
      'report.summary_ineligible': 'Su situación no cumple con los criterios actuales para los esquemas principales.',
      'scheme.pac101': 'Oferta "Impulso Bomba de Calor"',
      'scheme.iso101': 'Aislamiento de Ático por 1€',
      'scheme.ssc': 'Sistema Solar Combinado (SSC)',
      'scheme.mpr': 'MaPrimeRénov\' (Estándar)',
      'scheme.cee': 'Certificados de Ahorro de Energía (CEE)',
      'reason.ok_zone_h1': '✅ Prioridad Zona H1 para este esquema.',
      'reason.ok_zone_eligible': '✅ Zona climática elegible (H1 o H2).',
      'reason.ok_income_blue': '✅ Ingresos "Muy Modestos" (Azul) elegibles para tasa máxima.',
      'reason.ok_owner': '✅ Estado de propietario validado.',
      'reason.ok_house_age': '✅ Propiedad con más de 2 años.',
      'reason.ok_surface': '✅ Superficie suficiente para este esquema.',
      'reason.ok_heating_replace': '✅ Fomento del reemplazo de calefacción contaminante.',
      'reason.ok_tech_iso': '✅ Criterios técnicos ático validados (>80m², acceso OK).',
      'reason.ok_tech_ssc': '✅ Techo compatible con solar validado.',
      'reason.fail_zone': '❌ Zona climática no prioritaria para esta oferta específica.',
      'reason.fail_income_too_high': '❌ Los ingresos superan el techo reglamentario para esta ayuda.',
      'reason.fail_tenant_social': '❌ Esquema no aplicable a vivienda social.',
      'reason.fail_apartment': '❌ Oferta reservada para casas unifamiliares.',
      'reason.fail_new_build': '❌ Propiedad demasiado nueva (< 2 años).',
      'reason.fail_elec_heating': '❌ Reemplazo de calefacción eléctrica no subvencionado.',
      'reason.fail_surface_low': '❌ Superficie insuficiente para viabilidad económica.',
      'reason.fail_already_pac': '❌ Ya tiene una Bomba de Calor.',
      'reason.fail_tech_iso': '❌ Restricciones técnicas ático (área <80m² o sin acceso).',
      'reason.fail_tech_ssc': '❌ Techo incompatible (Orientación Norte o área insuficiente).',
  }
};